# Generated by Django 6.0.6 on 2026-07-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Science', 'Science & Tech'), ('History', 'History'), ('Biography', 'Biography'), ('General', 'General')], default='General', max_length=50),
        ),
    ]
